[[language]]
name = "fsharp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "css"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
indent = { tab-width = 4, unit = "    " }
auto-format = false

[[language]]
name = "vue"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
